spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/his_ar
    username: his_user
    password: his_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    stream:
      function:
        definition: eligibilityDeterminedConsumer;dataCapturedConsumer;applicationCreated
      bindings:
        applicationCreated-out-0:
          destination: application-created-topic
        dataCapturedConsumer-in-0:
          destination: data-captured-topic
          group: ar-group
        eligibilityDeterminedConsumer-in-0:
          destination: eligibility-determined-topic
          group: ar-group
      kafka:
        binder:
          brokers: kafka:29092

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    com.his.ar: DEBUG
    org.springframework.security: DEBUG

# Custom AR configuration
ar:
  encryption:
    secret: "3c5fG9H1j2K3l4N5p6Q7r8S9t0U1v2W3"
