package com.his.ar.model;

public enum WorkflowStatus {
    REGISTRATION_COMPLETE,
    DATA_COLLECTION_PENDING,
    DATA_COLLECTION_COMPLETED,
    ELIGIBILITY_CHECK_STARTED,
    ELIGIBILITY_APPROVED,
    ELIGIBILITY_REJECTED,
    BENEFIT_ISSUED
}
